"""initial schema - all core tables

Revision ID: dfbe300bcf75
Revises: 
Create Date: 2026-03-27 17:17:33.563836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbe300bcf75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('active_years', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_canonical', 'entities', ['canonical_name'], unique=False)
    op.create_index('idx_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_canonical_name'), 'entities', ['canonical_name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('fetch_strategy', sa.String(length=50), nullable=True),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('rate_limit_policy', sa.String(length=500), nullable=True),
    sa.Column('buyer_premium_policy', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_enabled', 'sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('comparables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('object_type', sa.String(length=200), nullable=True),
    sa.Column('material_tags', sa.JSON(), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comparable_source', 'comparables', ['source_name'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_lot_id', sa.String(length=200), nullable=False),
    sa.Column('lot_url', sa.String(length=500), nullable=False),
    sa.Column('canonical_title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lot_external_id', 'lots', ['external_lot_id'], unique=False)
    op.create_index('idx_lot_last_seen', 'lots', ['last_seen_at'], unique=False)
    op.create_index('idx_lot_source_id', 'lots', ['source_id'], unique=False)
    op.create_index('idx_lot_status', 'lots', ['status'], unique=False)
    op.create_table('enrichment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrichment_agent', 'enrichment_runs', ['agent_name'], unique=False)
    op.create_index('idx_enrichment_lot_id', 'enrichment_runs', ['lot_id'], unique=False)
    op.create_table('lot_fetches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_type', sa.String(length=50), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_html_path', sa.String(length=500), nullable=True),
    sa.Column('raw_text_path', sa.String(length=500), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lot_fetch_fetched_at', 'lot_fetches', ['fetched_at'], unique=False)
    op.create_index('idx_lot_fetch_lot_id', 'lot_fetches', ['lot_id'], unique=False)
    op.create_index('idx_lot_fetch_success', 'lot_fetches', ['success'], unique=False)
    op.create_table('lot_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lot_image_lot_id', 'lot_images', ['lot_id'], unique=False)
    op.create_table('lot_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('scoring_version', sa.String(length=50), nullable=False),
    sa.Column('arbitrage_score', sa.Float(), nullable=True),
    sa.Column('resale_arb_score', sa.Float(), nullable=True),
    sa.Column('taste_score', sa.Float(), nullable=True),
    sa.Column('wildcard_score', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('overall_watch_score', sa.Float(), nullable=True),
    sa.Column('explanation_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id')
    )
    op.create_index('idx_scores_arbitrage', 'lot_scores', ['arbitrage_score'], unique=False)
    op.create_index('idx_scores_resale_arb', 'lot_scores', ['resale_arb_score'], unique=False)
    op.create_index('idx_scores_overall_watch', 'lot_scores', ['overall_watch_score'], unique=False)
    op.create_index('idx_scores_taste', 'lot_scores', ['taste_score'], unique=False)
    op.create_index('idx_scores_wildcard', 'lot_scores', ['wildcard_score'], unique=False)
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_action_lot_id', 'user_actions', ['lot_id'], unique=False)
    op.create_index('idx_user_action_type', 'user_actions', ['action_type'], unique=False)
    op.create_table('enrichment_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrichment_run_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('score_primary', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrichment_run_id'], ['enrichment_runs.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrichment_output_lot_id', 'enrichment_outputs', ['lot_id'], unique=False)
    op.create_table('parsed_lot_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('lot_fetch_id', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_raw', sa.String(length=200), nullable=True),
    sa.Column('condition_text', sa.String(length=200), nullable=True),
    sa.Column('dimensions_text', sa.String(length=200), nullable=True),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('estimate_low', sa.Float(), nullable=True),
    sa.Column('estimate_high', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('auction_end_time', sa.DateTime(), nullable=True),
    sa.Column('time_left_text', sa.String(length=100), nullable=True),
    sa.Column('provenance_text', sa.Text(), nullable=True),
    sa.Column('seller_location', sa.String(length=200), nullable=True),
    sa.Column('auction_house_name', sa.String(length=200), nullable=True),
    sa.Column('raw_designer_mentions', sa.JSON(), nullable=True),
    sa.Column('raw_material_mentions', sa.JSON(), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_fetch_id'], ['lot_fetches.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parsed_lot_id', 'parsed_lot_fields', ['lot_id'], unique=False)
    op.create_table('normalized_lot_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('parsed_lot_fields_id', sa.Integer(), nullable=True),
    sa.Column('normalizer_version', sa.String(length=50), nullable=False),
    sa.Column('designer_entity_id', sa.Integer(), nullable=True),
    sa.Column('producer_entity_id', sa.Integer(), nullable=True),
    sa.Column('object_type_id', sa.String(length=100), nullable=True),
    sa.Column('era_label', sa.String(length=100), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('normalized_category', sa.String(length=200), nullable=True),
    sa.Column('normalization_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['designer_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['parsed_lot_fields_id'], ['parsed_lot_fields.id'], ),
    sa.ForeignKeyConstraint(['producer_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_normalized_designer_id', 'normalized_lot_fields', ['designer_entity_id'], unique=False)
    op.create_index('idx_normalized_lot_id', 'normalized_lot_fields', ['lot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_normalized_lot_id', table_name='normalized_lot_fields')
    op.drop_index('idx_normalized_designer_id', table_name='normalized_lot_fields')
    op.drop_table('normalized_lot_fields')
    op.drop_index('idx_parsed_lot_id', table_name='parsed_lot_fields')
    op.drop_table('parsed_lot_fields')
    op.drop_index('idx_enrichment_output_lot_id', table_name='enrichment_outputs')
    op.drop_table('enrichment_outputs')
    op.drop_index('idx_user_action_type', table_name='user_actions')
    op.drop_index('idx_user_action_lot_id', table_name='user_actions')
    op.drop_table('user_actions')
    op.drop_index('idx_scores_wildcard', table_name='lot_scores')
    op.drop_index('idx_scores_taste', table_name='lot_scores')
    op.drop_index('idx_scores_overall_watch', table_name='lot_scores')
    op.drop_index('idx_scores_resale_arb', table_name='lot_scores')
    op.drop_index('idx_scores_arbitrage', table_name='lot_scores')
    op.drop_table('lot_scores')
    op.drop_index('idx_lot_image_lot_id', table_name='lot_images')
    op.drop_table('lot_images')
    op.drop_index('idx_lot_fetch_success', table_name='lot_fetches')
    op.drop_index('idx_lot_fetch_lot_id', table_name='lot_fetches')
    op.drop_index('idx_lot_fetch_fetched_at', table_name='lot_fetches')
    op.drop_table('lot_fetches')
    op.drop_index('idx_enrichment_lot_id', table_name='enrichment_runs')
    op.drop_index('idx_enrichment_agent', table_name='enrichment_runs')
    op.drop_table('enrichment_runs')
    op.drop_index('idx_lot_status', table_name='lots')
    op.drop_index('idx_lot_source_id', table_name='lots')
    op.drop_index('idx_lot_last_seen', table_name='lots')
    op.drop_index('idx_lot_external_id', table_name='lots')
    op.drop_table('lots')
    op.drop_index('idx_comparable_source', table_name='comparables')
    op.drop_table('comparables')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index('idx_source_enabled', table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_entities_canonical_name'), table_name='entities')
    op.drop_index('idx_entity_type', table_name='entities')
    op.drop_index('idx_entity_canonical', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
