import { LotCard } from './types';

export const MOCK_LOTS: LotCard[] = [
  {
    id: 1,
    title: 'HANS J. WEGNER. Lounge chair, model GE290, GETAMA, Denmark.',
    source: 'auctionet',
    lot_url: 'https://auctionet.com/en/1234567-hans-wegner-lounge-chair',
    current_bid: 320,
    estimate_low: 400,
    estimate_high: 600,
    currency: 'EUR',
    auction_end_time: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    time_remaining: '6 hours',
    image_url: 'https://images.auctionet.com/thumbs/large_item_5001970_d165a8d953.jpg',
    labels: ['Strong Arbitrage', 'Norway Gap'],
    scores: { arbitrage: 0.87, taste: 0.81, wildcard: 0.4, urgency: 0.9 },
    ai_value_low: 900,
    ai_value_high: 1400,
    seller_location: 'Malmö, Sweden',
    landed_cost_eur: 420,
    expected_resale_eur: 1100,
    max_bid_eur: 480,
    conviction: 'high',
    rationale: 'Wegner GE290 consistently sells above estimate at Scandinavian auctions. Current bid is significantly below fair value.',
    risk_flags: ['Upholstery condition unknown'],
  },
  {
    id: 2,
    title: 'FINN JUHL. Egypt chair, Niels Vodder, Denmark, 1940s.',
    source: 'auctionet',
    lot_url: 'https://auctionet.com/en/2345678-finn-juhl-egypt-chair',
    current_bid: null,
    estimate_low: 1200,
    estimate_high: 1800,
    currency: 'EUR',
    auction_end_time: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    time_remaining: '2 days',
    image_url: 'https://images.auctionet.com/thumbs/large_item_5006656_736fdd0715.jpg',
    labels: ['Taste Match', 'Rare Form'],
    scores: { arbitrage: 0.62, taste: 0.95, wildcard: 0.88, urgency: 0.3 },
    ai_value_low: 2200,
    ai_value_high: 3500,
    seller_location: 'Stockholm, Sweden',
    landed_cost_eur: 1400,
    expected_resale_eur: 2800,
    max_bid_eur: 1600,
    conviction: 'medium',
    rationale: 'Rare early Vodder example. Finn Juhl demand in Norway is strong — this form rarely surfaces at auction.',
    risk_flags: ['Attribution needs verification', 'High estimate already'],
  },
  {
    id: 3,
    title: 'BØRGE MOGENSEN. Sofa, model 2212, Fredericia Furniture.',
    source: 'auctionet',
    lot_url: 'https://auctionet.com/en/3456789-borge-mogensen-sofa',
    current_bid: 550,
    estimate_low: 552,
    estimate_high: 552,
    currency: 'EUR',
    auction_end_time: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    time_remaining: '18 hours',
    image_url: null,
    labels: ['Ending Soon'],
    scores: { arbitrage: 0.71, taste: 0.76, wildcard: 0.3, urgency: 0.75 },
    ai_value_low: 800,
    ai_value_high: 1200,
    seller_location: 'Malmö, Sweden',
    landed_cost_eur: 650,
    expected_resale_eur: 950,
    max_bid_eur: 700,
    conviction: 'medium',
    rationale: 'Classic Mogensen leather sofa. Solid arbitrage window if upholstery is in good shape.',
    risk_flags: ['No images available', 'Leather condition unknown'],
  },
];
