#!/usr/bin/env python3
"""Generate a daily auction report for sharing with partners."""
import json
import sys
import logging
from pathlib import Path
from datetime import datetime, timedelta, timezone

sys.path.insert(0, str(Path(__file__).parent.parent))

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def generate_report():
    from backend.database import SessionLocal, init_db
    from backend.models import Lot, LotScores, ParsedLotFields

    init_db()
    db = SessionLocal()

    now = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d")

    # --- Strong buys ---
    strong_buys = (
        db.query(LotScores, Lot, ParsedLotFields)
        .join(Lot, LotScores.lot_id == Lot.id)
        .join(ParsedLotFields, Lot.id == ParsedLotFields.lot_id)
        .filter(Lot.status == "active")
        .filter(LotScores.arbitrage_score >= 0.7)
        .order_by(LotScores.arbitrage_score.desc())
        .all()
    )

    # Deduplicate
    seen = set()
    unique_strong = []
    for ls, lot, pf in strong_buys:
        if lot.id not in seen:
            seen.add(lot.id)
            unique_strong.append((ls, lot, pf))

    # --- Ending within 24h ---
    cutoff = now + timedelta(hours=24)
    ending_soon = (
        db.query(Lot, ParsedLotFields, LotScores)
        .join(ParsedLotFields, Lot.id == ParsedLotFields.lot_id)
        .outerjoin(LotScores, Lot.id == LotScores.lot_id)
        .filter(Lot.status == "active")
        .filter(ParsedLotFields.auction_end_time <= cutoff)
        .filter(ParsedLotFields.auction_end_time >= now)
        .order_by(ParsedLotFields.auction_end_time.asc())
        .all()
    )
    seen_ending = set()
    unique_ending = []
    for lot, pf, ls in ending_soon:
        if lot.id not in seen_ending:
            seen_ending.add(lot.id)
            unique_ending.append((lot, pf, ls))

    # --- Pipeline stats ---
    total = db.query(Lot).count()
    active = db.query(Lot).filter(Lot.status == "active").count()
    filtered = db.query(Lot).filter(Lot.status == "filtered").count()
    scored = db.query(LotScores).count()

    db.close()

    # --- Build report ---
    lines = []
    lines.append(f"# Auction Vision — Daily Report ({today})")
    lines.append("")

    # Strong buys
    lines.append(f"## Strong Buys ({len(unique_strong)} lots with 3x+ potential)")
    lines.append("")
    if unique_strong:
        lines.append("| Lot | Item | Est | Resale Est | Mult | Conf | Ends |")
        lines.append("|-----|------|-----|-----------|------|------|------|")
        for ls, lot, pf in unique_strong[:20]:
            title = (pf.title or "?")[:45]
            est = f"{pf.estimate_low:.0f} EUR" if pf.estimate_low else "—"
            expl = ls.explanation_json or {}
            ai_lo = expl.get("ai_value_low")
            ai_hi = expl.get("ai_value_high")
            resale = f"{ai_lo:.0f}–{ai_hi:.0f}" if ai_lo and ai_hi else "—"
            conf = expl.get("estimate_confidence", "—")

            # Multiplier
            mult = "—"
            if ai_lo and ai_hi and pf.estimate_low and pf.estimate_low > 0:
                mid = (ai_lo + ai_hi) / 2
                m = mid / (pf.estimate_low * 1.2)
                mult = f"{m:.1f}x"

            ends = pf.auction_end_time.strftime("%b %d %H:%M") if pf.auction_end_time else "—"
            url = lot.lot_url or ""
            lines.append(f"| [{lot.external_lot_id}]({url}) | {title} | {est} | {resale} | {mult} | {conf} | {ends} |")
    else:
        lines.append("No strong buys found today.")
    lines.append("")

    # Ending soon
    lines.append(f"## Ending Within 24h ({len(unique_ending)} lots)")
    lines.append("")
    if unique_ending:
        for lot, pf, ls in unique_ending[:15]:
            title = (pf.title or "?")[:50]
            est = f"{pf.estimate_low:.0f} EUR" if pf.estimate_low else "—"
            arb = f"{ls.arbitrage_score:.0%}" if ls and ls.arbitrage_score else "—"
            ends = pf.auction_end_time.strftime("%b %d %H:%M") if pf.auction_end_time else "?"
            lines.append(f"- **{title}** | est {est} | arb {arb} | ends {ends} | [{lot.external_lot_id}]({lot.lot_url})")
    else:
        lines.append("No lots ending within 24h.")
    lines.append("")

    # Stats
    lines.append("## Pipeline Stats")
    lines.append("")
    lines.append(f"- Total lots: {total}")
    lines.append(f"- Active: {active}")
    lines.append(f"- Filtered: {filtered}")
    lines.append(f"- Scored: {scored}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Auction Vision*")

    report = "\n".join(lines)

    # Save report
    report_dir = Path("data/reports")
    report_dir.mkdir(exist_ok=True)
    report_path = report_dir / f"daily_{today}.md"
    report_path.write_text(report)

    print(report)
    logger.info(f"Report saved to {report_path}")
    return report


if __name__ == "__main__":
    generate_report()
